### ISSUE TITLE
It is feasible to load csv data set and test it here?

### ISSUE THREAD

**Issue by JafferWilson** [poloclub/ganlab#10]
I have got a csv data available here: https://gist.github.com/JafferWilson/3ab8ee88f3fc32e78579a1054aac757d  
Please let me know if I can visualize through the gan lab or not. I have tried it using with the Playground but the app it very resistive and do not allow more than 2 inputs.
Please can you help?

**Comment by minsukkahng** [comment]
Thank you for your interests! And sorry for my super late response. It's currently not supported. The four datasets we provide are hard-coded in `demo/ganlab_input_providers.ts`. But I do think it would be awesome if GAN Lab or Playground support that feature, and will consider it when we get a chance to update ours and develop new ones.

Cheers,
Minsuk
